user:
  half_size: 50

word:
  number_of_answers: 2
  per_page: 5

lesson:
  word_limit: 10

category:
  per_page: 5
  filter_type:
    all_words: "all_words"
    learned: "learned"
    not_learned: "not_learned"

activity:
  per_page: 10
